apiVersion: v1
kind: Service
metadata:
  name: infinispan-embedded
spec:
  clusterIP: None
  ports:
  - name: discovery
    port: 7800
    protocol: TCP
    targetPort: 7800
  selector:
    name: cart-app
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}